/* ============================================================
   ONZE — Les Icônes v1 (design/icones.md) : groupes I et II
   (22 quêtes simples) + le duo Gus & Titi (nº38, prioritaire).
   Chaque Icône : sa fiche de joueur (icone: true → +15 % de stats,
   copie unique) et sa quête — test(partie) dit si c'est débloqué,
   progression(partie) affiche l'avancement.
   Les compteurs vivent dans partie.compteurs (partie.html).

   LE LIEN AVEC LES JOUEURS : chaque quête déclare, juste sous sa
   condition, soit concerne(joueur) — les joueurs qu'elle pointe —
   soit sansJoueur: true. La règle est dans quetes-lien.js : une
   quête ne pointe un joueur que si sa condition nomme un trait de
   ce joueur (École, archétype, poste, coût, nom, Unique). Aucune
   quête n'a le droit de rester muette : le garde-fou
   tests/quetes-lien.spec.js sort rouge si l'une des deux
   déclarations manque.
   ============================================================ */

const ONZE_ICONES = (() => {
  const c = (partie, cle) => (partie.compteurs && partie.compteurs[cle]) || 0;
  const slotsStaff = (j) => (j.staffCartes || []).length + (j.specialisations || []).length * 2;

  const liste = [
    /* ---------- I. Ouverture ---------- */
    { id: "globe-trotteur", nom: "Le Globe-Trotteur", cout: 2, poste: "MIL", ecole: "Les Internationaux", archetype: "Moteur",
      condition: "Relancer le mercato 4 fois avant le Mercato d'hiver",
      sansJoueur: true,
      identite: "A joué sur 4 continents ; sait tout faire un peu.",
      test: (p) => p.manche < 8 && c(p, "relances") >= 4,
      progression: (p) => Math.min(c(p, "relances"), 4) + "/4" },
    { id: "chouchou", nom: "Le Chouchou du Staff", cout: 2, poste: "ATT", ecole: "Les Pros", archetype: "Renard",
      condition: "Aligner un joueur portant 2 cartes Staff",
      sansJoueur: true, // n'importe quel joueur : ne distingue personne
      identite: "Le staff le bichonne.",
      test: (p) => p.terrain.some((j) => slotsStaff(j) >= 2),
      progression: (p) => Math.max(0, ...p.terrain.map(slotsStaff)) + "/2" },
    { id: "surdoue", nom: "Le Surdoué", cout: 3, poste: "MIL", ecole: "L'Académie", archetype: "Créateur",
      condition: "Aligner un Académicien avec 2 cartes Staff",
      concerne: (j) => j.ecole === "L'Académie" || j.ecoleBonus === "L'Académie",
      identite: "Le crack que tout le centre regarde.",
      test: (p) => p.terrain.some((j) => j.ecole === "L'Académie" && slotsStaff(j) >= 2),
      progression: (p) => (p.terrain.some((j) => j.ecole === "L'Académie") ? "Académicien aligné · " : "") + "staff 0/2" },
    { id: "la-tour", nom: "La Tour", cout: 3, poste: "DÉF", ecole: "Kick & Rush", archetype: "Mur",
      condition: "Gagner 5 duels aériens dans un même match",
      sansJoueur: true,
      identite: "2m02, imbattable dans les airs.",
      test: (p) => c(p, "aeriensMatch") >= 5,
      progression: (p) => "record " + c(p, "aeriensMatch") + "/5" },
    { id: "le-patient", nom: "Le Patient", cout: 2, poste: "MIL", ecole: "Les Pros", archetype: "Créateur",
      condition: "Verrouiller la boutique 2 fois",
      sansJoueur: true,
      identite: "Il attend son heure — et elle arrive.",
      test: (p) => c(p, "verrous") >= 2,
      progression: (p) => c(p, "verrous") + "/2" },
    { id: "le-trader", nom: "Le Trader", cout: 2, poste: "DÉF", ecole: "Les Revanchards", archetype: "Sentinelle",
      condition: "Vendre 3 joueurs dans la même manche",
      sansJoueur: true,
      identite: "Chaque départ rapporte.",
      test: (p) => c(p, "ventesManche") >= 3,
      progression: (p) => c(p, "ventesManche") + "/3 cette manche" },
    { id: "enfant-gate", nom: "L'Enfant Gâté", cout: 2, poste: "ATT", ecole: "École de la Rue", archetype: "Chanceux",
      condition: "Ouvrir un orbe or",
      sansJoueur: true,
      identite: "Né sous une bonne étoile, littéralement.",
      test: (p) => c(p, "orbeOr") >= 1,
      progression: (p) => c(p, "orbeOr") ? "fait !" : "0/1" },
    { id: "le-banquier", nom: "Le Banquier", cout: 3, poste: "MIL", ecole: "Les Pros", archetype: "Mentor",
      condition: "Atteindre 20M en caisse",
      sansJoueur: true,
      identite: "Défend chaque million.",
      test: (p) => p.or >= 20,
      progression: (p) => p.or + "/20M" },
    { id: "le-fidele", nom: "Le Fidèle", cout: 3, poste: "DÉF", ecole: "Le Douzième Homme", archetype: "Mur",
      condition: "Jouer 3 manches avec un onze inchangé",
      sansJoueur: true,
      identite: "15 ans au club, le public l'adore.",
      test: (p) => c(p, "onzeInchange") >= 3,
      progression: (p) => c(p, "onzeInchange") + "/3" },
    { id: "bourreau", nom: "Le Bourreau des Petits", cout: 2, poste: "ATT", ecole: "Kick & Rush", archetype: "Finisseur",
      condition: "Gagner un amical par 3+ buts d'écart",
      sansJoueur: true,
      identite: "Marque toujours contre les faibles.",
      test: (p) => c(p, "bourreau") >= 1,
      progression: (p) => c(p, "bourreau") ? "fait !" : "0/1" },
    { id: "espion", nom: "L'Espion", cout: 2, poste: "MIL", ecole: "Les Internationaux", archetype: "Sentinelle",
      condition: "Scouter 4 adversaires dans la même manche",
      sansJoueur: true,
      identite: "Il sait déjà tout.",
      test: (p) => c(p, "scoutsManche") >= 4,
      progression: (p) => c(p, "scoutsManche") + "/4 cette manche" },
    { id: "repeche", nom: "Le Repêché", cout: 3, poste: "MIL", ecole: "Les Revanchards", archetype: "Moteur",
      condition: "Choisir en premier au Mercato d'hiver",
      sansJoueur: true,
      identite: "Personne n'en voulait ; tout le monde le regrette.",
      test: (p) => c(p, "premierHiver") >= 1,
      progression: (p) => c(p, "premierHiver") ? "fait !" : "sois dernier au prestige à la manche 8" },

    /* ---------- II. Milieu de partie ---------- */
    { id: "heritier", nom: "L'Héritier", cout: 4, poste: "ATT", ecole: "L'Académie", archetype: "Finisseur",
      condition: "Aligner une 2★ coût 4 avec 2 spécialisations",
      concerne: (j) => j.cout === 4,
      identite: "Le fils spirituel de la Doyenne.",
      test: (p) => p.terrain.some((j) => (j.etoiles || 1) >= 2 && j.cout === 4 && (j.specialisations || []).length >= 2),
      progression: () => "2★ coût 4 + 2 🧪" },
    { id: "idole", nom: "L'Idole des Ultras", cout: 4, poste: "MIL", ecole: "Le Douzième Homme", archetype: "Guerrier",
      condition: "Accumuler 20 Ferveur",
      sansJoueur: true,
      identite: "Le stade gronde avec lui.",
      test: (p) => c(p, "ferveur") >= 20,
      progression: (p) => c(p, "ferveur") + "/20 🔥" },
    { id: "mur-originel", nom: "Le Mur Originel", cout: 4, poste: "GAR", ecole: "Catenaccio", archetype: "Mur",
      condition: "3 manches consécutives sans encaisser",
      sansJoueur: true,
      identite: "Le gardien dont tous les Murs descendent.",
      test: (p) => c(p, "sansEncaisser") >= 3,
      progression: (p) => c(p, "sansEncaisser") + "/3" },
    { id: "revenant", nom: "L'Éternel Revenant", cout: 4, poste: "ATT", ecole: "La Grinta", archetype: "Renard",
      condition: "Gagner un match après avoir été mené de 2 buts",
      sansJoueur: true,
      identite: "Revient toujours — c'est écrit.",
      test: (p) => c(p, "remontada") >= 1,
      progression: (p) => c(p, "remontada") ? "fait !" : "0/1" },
    { id: "cobaye", nom: "Le Cobaye", cout: 3, poste: "MIL", ecole: "Les Pros", archetype: "Guerrier",
      condition: "Créer une spécialisation 🧪",
      sansJoueur: true,
      identite: "Le staff teste tout sur lui.",
      test: (p) => c(p, "specsCreees") >= 1,
      progression: (p) => c(p, "specsCreees") ? "fait !" : "0/1" },
    { id: "binational", nom: "Le Binational", cout: 4, poste: "ATT", ecole: "Les Internationaux", archetype: "Virtuose",
      condition: "Poser un emblème (Passeport)",
      sansJoueur: true,
      identite: "Deux hymnes, zéro état d'âme.",
      test: (p) => c(p, "emblemes") >= 1,
      progression: (p) => c(p, "emblemes") ? "fait !" : "0/1" },
    { id: "le-systeme", nom: "Le Système", cout: 4, poste: "MIL", ecole: "Football Total", archetype: "Mentor",
      condition: "Activer 4 familles en même temps",
      sansJoueur: true,
      identite: "Il EST la tactique.",
      test: (p, apercu) => apercu && apercu.synergies.length >= 4,
      progression: (p, apercu) => (apercu ? apercu.synergies.length : 0) + "/4 familles" },
    { id: "comptable", nom: "Le Comptable du Board", cout: 3, poste: "DÉF", ecole: "Les Pros", archetype: "Sentinelle",
      condition: "Choisir une Philosophie économique",
      sansJoueur: true,
      identite: "Défend la surface comme un budget.",
      test: (p) => p.philosophies.some((nom) => ["Droits TV majorés", "Mécènes", "Guichets fermés", "Trésor de guerre"].includes(nom)),
      progression: () => "au choix des manches 4/7/10" },
    { id: "phenix", nom: "Le Phénix", cout: 4, poste: "ATT", ecole: "La Grinta", archetype: "Renard",
      condition: "Gagner juste après 3 défaites consécutives",
      sansJoueur: true,
      identite: "Renaît de chaque série noire.",
      test: (p) => c(p, "phenix") >= 1,
      progression: (p) => c(p, "phenix") ? "fait !" : "série actuelle : " + (p.coachs[0].serie < 0 ? -p.coachs[0].serie + " défaites" : "—") },
    { id: "serrurier", nom: "Le Serrurier", cout: 4, poste: "GAR", ecole: "Catenaccio", archetype: "Mur",
      condition: "Finir un match PvP 0-0",
      sansJoueur: true,
      identite: "Le 0-0 est son chef-d'œuvre.",
      test: (p) => c(p, "serrurier") >= 1,
      progression: (p) => c(p, "serrurier") ? "fait !" : "0/1" },

    /* ---------- V. Le duo prioritaire ---------- */
    { id: "gus-et-titi", nom: "Gus & Titi — les Increvables", cout: 4, poste: "DUO", ecole: "Le Douzième Homme", archetype: "",
      condition: "Garder Gus OU Titi titulaire jusqu'à la manche 10",
      concerne: (j) => j.nom === "Gus" || j.nom === "Titi",
      identite: "Les réservistes du centre devenus légendes — la récompense des fidèles.",
      duo: [
        { nom: "Gus", cout: 4, poste: "GAR", ecole: "Le Douzième Homme", archetype: "Mur", unique: null, icone: true,
          description: "L'increvable gardien du centre — le public l'a rendu légendaire." },
        { nom: "Titi", cout: 4, poste: "ATT", ecole: "Le Douzième Homme", archetype: "Renard", unique: null, icone: true,
          description: "L'increvable renard du centre — il n'a jamais quitté le club." },
      ],
      test: (p) => p.manche >= 10 && p.terrain.some((j) => (j.nom === "Gus" || j.nom === "Titi") && !j.icone),
      progression: (p) => p.terrain.some((j) => (j.nom === "Gus" || j.nom === "Titi") && !j.icone)
        ? "manche " + Math.min(p.manche, 10) + "/10 — tiens bon !" : "Gus et Titi ne sont plus titulaires…" },

    /* ---------- III. Fin de partie ---------- */
    { id: "mercenaire", nom: "Le Mercenaire", cout: 5, poste: "ATT", ecole: "", archetype: "Finisseur",
      condition: "Dépenser 60M cumulés au mercato",
      sansJoueur: true,
      identite: "Joue pour le plus offrant.",
      test: (p) => c(p, "depensesMercato") >= 60,
      progression: (p) => c(p, "depensesMercato") + "/60M dépensés" },
    { id: "legende-vivante", nom: "La Légende Vivante", cout: 5, poste: "MIL", ecole: "Le Douzième Homme", archetype: "Créateur",
      condition: "Accumuler 150 Ferveur",
      sansJoueur: true,
      identite: "Le stade chante son nom avant qu'il touche le ballon.",
      test: (p) => c(p, "ferveur") >= 150,
      progression: (p) => c(p, "ferveur") + "/150 🔥" },
    { id: "grand-renard", nom: "Le Grand Renard", cout: 5, poste: "ATT", ecole: "Catenaccio", archetype: "Renard",
      condition: "Marquer 12 buts cumulés dans la partie",
      sansJoueur: true,
      identite: "Il ne court pas : il apparaît.",
      test: (p) => c(p, "butsCumules") >= 12,
      progression: (p) => c(p, "butsCumules") + "/12 buts" },
    { id: "doyenne", nom: "La Doyenne", cout: 5, poste: "MIL", ecole: "L'Académie", archetype: "Mentor",
      condition: "Monter une Légende 3★ coût 1",
      concerne: (j) => j.cout === 1,
      identite: "L'entraîneuse mythique — tes Espoirs jouent un cran au-dessus.",
      test: (p) => [...p.terrain, ...p.banc].some((j) => (j.etoiles || 1) >= 3 && j.cout === 1),
      progression: (p) => { const m = Math.max(0, ...[...p.terrain, ...p.banc].filter((j) => j.cout === 1).map((j) => j.etoiles || 1)); return m + "★/3★ (coût 1)"; } },
    { id: "invincible", nom: "L'Invincible", cout: 5, poste: "DÉF", ecole: "Kick & Rush", archetype: "Capitaine",
      condition: "Série de 5 victoires",
      sansJoueur: true,
      identite: "N'a jamais perdu un derby — attention : c'est un Capitaine.",
      test: (p) => p.coachs && p.coachs.find((x) => !x.ia) && p.coachs.find((x) => !x.ia).serie >= 5,
      progression: (p) => Math.max(0, (p.coachs && p.coachs.find((x) => !x.ia) || {}).serie || 0) + "/5 🔥" },
    { id: "poete", nom: "Le Poète du Stade", cout: 5, poste: "MIL", ecole: "École de la Rue", archetype: "Créateur",
      condition: "Accumuler 100 Ferveur",
      sansJoueur: true,
      identite: "Chaque passe est un vers ; le public paie pour le lire.",
      test: (p) => c(p, "ferveur") >= 100,
      progression: (p) => c(p, "ferveur") + "/100 🔥" },
    { id: "fossoyeur", nom: "Le Fossoyeur", cout: 5, poste: "ATT", ecole: "Catenaccio", archetype: "Finisseur",
      condition: "Porter le coup final à un club (l'éliminer)",
      sansJoueur: true,
      identite: "Marque le but qui enterre.",
      test: (p) => c(p, "coupsDeGrace") >= 1,
      progression: (p) => c(p, "coupsDeGrace") ? "fait !" : "0/1 élimination" },
    { id: "produit-du-labo", nom: "Le Produit du Labo", cout: 5, poste: "ATT", ecole: "Les Pros", archetype: "Guerrier",
      condition: "Avoir 6 spécialisations sur le terrain",
      sansJoueur: true,
      identite: "Créé en éprouvette par le staff.",
      test: (p) => p.terrain.reduce((t, j) => t + (j.specialisations || []).length, 0) >= 6,
      progression: (p) => p.terrain.reduce((t, j) => t + (j.specialisations || []).length, 0) + "/6 🧪" },

    /* ---------- IV. Les Légendes coût 6-7 ---------- */
    { id: "architecte", nom: "L'Architecte", cout: 6, poste: "MIL", ecole: "Tiki-Taka", archetype: "Créateur",
      condition: "Aligner 5 joueurs Tiki-Taka",
      concerne: (j) => j.ecole === "Tiki-Taka" || j.ecoleBonus === "Tiki-Taka",
      identite: "Le cerveau absolu — le terrain est son plan.",
      test: (p) => p.terrain.filter((j) => j.ecole === "Tiki-Taka" || j.ecoleBonus === "Tiki-Taka").length >= 5,
      progression: (p) => p.terrain.filter((j) => j.ecole === "Tiki-Taka" || j.ecoleBonus === "Tiki-Taka").length + "/5 🎹" },
    { id: "selectionneur", nom: "Le Sélectionneur", cout: 6, poste: "GAR", ecole: "Les Internationaux", archetype: "Capitaine",
      condition: "11 titulaires sans réserviste + 5 familles actives",
      sansJoueur: true,
      identite: "Il a entraîné trois nations ; il joue maintenant.",
      test: (p, apercu) => p.terrain.length >= 11 && p.terrain.every((j) => j.cout >= 1) &&
        apercu && apercu.synergies.length >= 5,
      progression: (p, apercu) => p.terrain.filter((j) => j.cout >= 1).length + "/11 pros · " +
        ((apercu && apercu.synergies.length) || 0) + "/5 familles" },
    { id: "huracan", nom: "El Huracán", cout: 6, poste: "ATT", ecole: "La Grinta", archetype: "Finisseur",
      condition: "3 victoires d'affilée par 3+ d'écart",
      sansJoueur: true,
      identite: "La tempête qui rase tout.",
      test: (p) => c(p, "serieGrosEcarts") >= 3,
      progression: (p) => c(p, "serieGrosEcarts") + "/3 tempêtes" },
    { id: "fantasma", nom: "O Fantasma", cout: 7, poste: "ATT", ecole: "École de la Rue", archetype: "Virtuose",
      condition: "Niveau de club 10 + 7 joueurs de la Rue",
      concerne: (j) => j.ecole === "École de la Rue" || j.ecoleBonus === "École de la Rue",
      identite: "Le dieu de la rue — personne ne l'a jamais vu défendre.",
      test: (p) => p.niveau >= 10 && p.terrain.filter((j) => j.ecole === "École de la Rue" || j.ecoleBonus === "École de la Rue").length >= 7,
      progression: (p) => "niv " + p.niveau + "/10 · " + p.terrain.filter((j) => j.ecole === "École de la Rue" || j.ecoleBonus === "École de la Rue").length + "/7 🛹" },
    { id: "president-joueur", nom: "Le Président-Joueur", cout: 7, poste: "MIL", ecole: "", archetype: "Capitaine",
      condition: "Niveau 10 + 80M en caisse",
      sansJoueur: true,
      identite: "Il a acheté le club pour se titulariser.",
      test: (p) => p.niveau >= 10 && p.or >= 80,
      progression: (p) => "niv " + p.niveau + "/10 · " + p.or + "/80M" },

    /* ---------- V. Les Duos — deux joueurs, une carte ---------- */
    { id: "la-samba", nom: "Malandro & Didico — la Samba", cout: 7, poste: "DUO", ecole: "École de la Rue", archetype: "",
      condition: "3 manches avec 5+ École de la Rue",
      concerne: (j) => j.ecole === "École de la Rue" || j.ecoleBonus === "École de la Rue",
      identite: "Le dribble de l'un, la lambretta de l'autre.",
      duo: [
        { nom: "Malandro", cout: 4, poste: "ATT", ecole: "École de la Rue", archetype: "Virtuose", unique: null, icone: true,
          description: "La version légende du roi du dribble — la rue en parle encore." },
        { nom: "Didico", cout: 3, poste: "MIL", ecole: "École de la Rue", archetype: "Créateur", unique: null, icone: true,
          description: "La version légende du sorcier de la lambretta." },
      ],
      test: (p) => c(p, "manchesRue5") >= 3,
      progression: (p) => c(p, "manchesRue5") + "/3 manches à 5+ 🛹" },
    { id: "billy-jamie", nom: "Billy & Jamie — le Kick & Rush éternel", cout: 5, poste: "ATT", ecole: "Kick & Rush", archetype: "Finisseur",
      condition: "Aligner Billy et Jamie ensemble 4 manches",
      concerne: (j) => j.nom === "Billy" || j.nom === "Jamie",
      identite: "Le pivot et le surgisseur, fusionnés en une seule carte.",
      test: (p) => c(p, "manchesBillyJamie") >= 4,
      progression: (p) => c(p, "manchesBillyJamie") + "/4 manches ensemble" },
    { id: "la-remontada", nom: "Duarte & Perotti — la Remontada", cout: 7, poste: "DUO", ecole: "La Grinta", archetype: "",
      condition: "Aligner 2 Uniques Grinta pendant 3 manches",
      concerne: (j) => !!j.unique && (j.ecole === "La Grinta" || j.ecoleBonus === "La Grinta"),
      identite: "Le but de la 90ᵉ et l'arrêt de la 91ᵉ.",
      duo: [
        { nom: "Duarte", cout: 4, poste: "ATT", ecole: "La Grinta", archetype: "Renard", unique: null, icone: true,
          description: "Le but de la 90ᵉ — il revient toujours." },
        { nom: "Perotti", cout: 3, poste: "GAR", ecole: "La Grinta", archetype: "Capitaine", unique: null, icone: true,
          description: "L'arrêt de la 91ᵉ — le capitaine des causes perdues." },
      ],
      test: (p) => c(p, "manchesGrintaUniques") >= 3,
      progression: (p) => c(p, "manchesGrintaUniques") + "/3 manches 🐺" },
    { id: "jumeaux-bamana", nom: "Les Jumeaux Bamana", cout: 5, poste: "DUO", ecole: "L'Académie", archetype: "",
      condition: "Réussir 2 fusions dans la même manche",
      sansJoueur: true,
      identite: "Sékou avait un frère — ils jouent par télépathie.",
      duo: [
        { nom: "Issa B.", cout: 3, poste: "DÉF", ecole: "L'Académie", archetype: "Mur", unique: null, icone: true,
          description: "Le jumeau silencieux — il défend ce que l'autre imagine." },
        { nom: "Demba B.", cout: 2, poste: "MIL", ecole: "L'Académie", archetype: "Moteur", unique: null, icone: true,
          description: "Le jumeau du milieu — il court pour deux." },
      ],
      test: (p) => c(p, "fusionsManche") >= 2,
      progression: (p) => c(p, "fusionsManche") + "/2 fusions cette manche" },
  ];

  return { liste, parId: (id) => liste.find((x) => x.id === id) };
})();
if (typeof module !== "undefined") module.exports = ONZE_ICONES;
