/* ============================================================
   ONZE — Les Icônes v1 (design/icones.md) : groupes I et II
   (22 quêtes simples) + le duo Gus & Titi (nº38, prioritaire).
   Chaque Icône : sa fiche de joueur (icone: true → +15 % de stats,
   copie unique) et sa quête — test(partie) dit si c'est débloqué,
   progression(partie) affiche l'avancement.
   Les compteurs vivent dans partie.compteurs (partie.html).
   ============================================================ */

const ONZE_ICONES = (() => {
  const c = (partie, cle) => (partie.compteurs && partie.compteurs[cle]) || 0;
  const slotsStaff = (j) => (j.staffCartes || []).length + (j.specialisations || []).length * 2;

  const liste = [
    /* ---------- I. Ouverture ---------- */
    { id: "globe-trotteur", nom: "Le Globe-Trotteur", cout: 2, poste: "MIL", ecole: "Les Internationaux", archetype: "Moteur",
      condition: "Relancer le mercato 4 fois avant le Mercato d'hiver",
      identite: "A joué sur 4 continents ; sait tout faire un peu.",
      test: (p) => p.manche < 8 && c(p, "relances") >= 4,
      progression: (p) => Math.min(c(p, "relances"), 4) + "/4" },
    { id: "chouchou", nom: "Le Chouchou du Staff", cout: 2, poste: "ATT", ecole: "Les Pros", archetype: "Renard",
      condition: "Aligner un joueur portant 2 cartes Staff",
      identite: "Le staff le bichonne.",
      test: (p) => p.terrain.some((j) => slotsStaff(j) >= 2),
      progression: (p) => Math.max(0, ...p.terrain.map(slotsStaff)) + "/2" },
    { id: "surdoue", nom: "Le Surdoué", cout: 3, poste: "MIL", ecole: "L'Académie", archetype: "Créateur",
      condition: "Aligner un Académicien avec 2 cartes Staff",
      identite: "Le crack que tout le centre regarde.",
      test: (p) => p.terrain.some((j) => j.ecole === "L'Académie" && slotsStaff(j) >= 2),
      progression: (p) => (p.terrain.some((j) => j.ecole === "L'Académie") ? "Académicien aligné · " : "") + "staff 0/2" },
    { id: "la-tour", nom: "La Tour", cout: 3, poste: "DÉF", ecole: "Kick & Rush", archetype: "Mur",
      condition: "Gagner 5 duels aériens dans un même match",
      identite: "2m02, imbattable dans les airs.",
      test: (p) => c(p, "aeriensMatch") >= 5,
      progression: (p) => "record " + c(p, "aeriensMatch") + "/5" },
    { id: "le-patient", nom: "Le Patient", cout: 2, poste: "MIL", ecole: "Les Pros", archetype: "Créateur",
      condition: "Verrouiller la boutique 2 fois",
      identite: "Il attend son heure — et elle arrive.",
      test: (p) => c(p, "verrous") >= 2,
      progression: (p) => c(p, "verrous") + "/2" },
    { id: "le-trader", nom: "Le Trader", cout: 2, poste: "DÉF", ecole: "Les Revanchards", archetype: "Sentinelle",
      condition: "Vendre 3 joueurs dans la même manche",
      identite: "Chaque départ rapporte.",
      test: (p) => c(p, "ventesManche") >= 3,
      progression: (p) => c(p, "ventesManche") + "/3 cette manche" },
    { id: "enfant-gate", nom: "L'Enfant Gâté", cout: 2, poste: "ATT", ecole: "École de la Rue", archetype: "Chanceux",
      condition: "Ouvrir un orbe or",
      identite: "Né sous une bonne étoile, littéralement.",
      test: (p) => c(p, "orbeOr") >= 1,
      progression: (p) => c(p, "orbeOr") ? "fait !" : "0/1" },
    { id: "le-banquier", nom: "Le Banquier", cout: 3, poste: "MIL", ecole: "Les Pros", archetype: "Mentor",
      condition: "Atteindre 20M en caisse",
      identite: "Défend chaque million.",
      test: (p) => p.or >= 20,
      progression: (p) => p.or + "/20M" },
    { id: "le-fidele", nom: "Le Fidèle", cout: 3, poste: "DÉF", ecole: "Le Douzième Homme", archetype: "Mur",
      condition: "Jouer 3 manches avec un onze inchangé",
      identite: "15 ans au club, le public l'adore.",
      test: (p) => c(p, "onzeInchange") >= 3,
      progression: (p) => c(p, "onzeInchange") + "/3" },
    { id: "bourreau", nom: "Le Bourreau des Petits", cout: 2, poste: "ATT", ecole: "Kick & Rush", archetype: "Finisseur",
      condition: "Gagner un amical par 3+ buts d'écart",
      identite: "Marque toujours contre les faibles.",
      test: (p) => c(p, "bourreau") >= 1,
      progression: (p) => c(p, "bourreau") ? "fait !" : "0/1" },
    { id: "espion", nom: "L'Espion", cout: 2, poste: "MIL", ecole: "Les Internationaux", archetype: "Sentinelle",
      condition: "Scouter 4 adversaires dans la même manche",
      identite: "Il sait déjà tout.",
      test: (p) => c(p, "scoutsManche") >= 4,
      progression: (p) => c(p, "scoutsManche") + "/4 cette manche" },
    { id: "repeche", nom: "Le Repêché", cout: 3, poste: "MIL", ecole: "Les Revanchards", archetype: "Moteur",
      condition: "Choisir en premier au Mercato d'hiver",
      identite: "Personne n'en voulait ; tout le monde le regrette.",
      test: (p) => c(p, "premierHiver") >= 1,
      progression: (p) => c(p, "premierHiver") ? "fait !" : "sois dernier au prestige à la manche 8" },

    /* ---------- II. Milieu de partie ---------- */
    { id: "heritier", nom: "L'Héritier", cout: 4, poste: "ATT", ecole: "L'Académie", archetype: "Finisseur",
      condition: "Aligner une 2★ coût 4 avec 2 spécialisations",
      identite: "Le fils spirituel de la Doyenne.",
      test: (p) => p.terrain.some((j) => (j.etoiles || 1) >= 2 && j.cout === 4 && (j.specialisations || []).length >= 2),
      progression: () => "2★ coût 4 + 2 🧪" },
    { id: "idole", nom: "L'Idole des Ultras", cout: 4, poste: "MIL", ecole: "Le Douzième Homme", archetype: "Guerrier",
      condition: "Accumuler 20 Ferveur",
      identite: "Le stade gronde avec lui.",
      test: (p) => c(p, "ferveur") >= 20,
      progression: (p) => c(p, "ferveur") + "/20 🔥" },
    { id: "mur-originel", nom: "Le Mur Originel", cout: 4, poste: "GAR", ecole: "Catenaccio", archetype: "Mur",
      condition: "3 manches consécutives sans encaisser",
      identite: "Le gardien dont tous les Murs descendent.",
      test: (p) => c(p, "sansEncaisser") >= 3,
      progression: (p) => c(p, "sansEncaisser") + "/3" },
    { id: "revenant", nom: "L'Éternel Revenant", cout: 4, poste: "ATT", ecole: "La Grinta", archetype: "Renard",
      condition: "Gagner un match après avoir été mené de 2 buts",
      identite: "Revient toujours — c'est écrit.",
      test: (p) => c(p, "remontada") >= 1,
      progression: (p) => c(p, "remontada") ? "fait !" : "0/1" },
    { id: "cobaye", nom: "Le Cobaye", cout: 3, poste: "MIL", ecole: "Les Pros", archetype: "Guerrier",
      condition: "Créer une spécialisation 🧪",
      identite: "Le staff teste tout sur lui.",
      test: (p) => c(p, "specsCreees") >= 1,
      progression: (p) => c(p, "specsCreees") ? "fait !" : "0/1" },
    { id: "binational", nom: "Le Binational", cout: 4, poste: "ATT", ecole: "Les Internationaux", archetype: "Virtuose",
      condition: "Poser un emblème (Passeport)",
      identite: "Deux hymnes, zéro état d'âme.",
      test: (p) => c(p, "emblemes") >= 1,
      progression: (p) => c(p, "emblemes") ? "fait !" : "0/1" },
    { id: "le-systeme", nom: "Le Système", cout: 4, poste: "MIL", ecole: "Football Total", archetype: "Mentor",
      condition: "Activer 4 familles en même temps",
      identite: "Il EST la tactique.",
      test: (p, apercu) => apercu && apercu.synergies.length >= 4,
      progression: (p, apercu) => (apercu ? apercu.synergies.length : 0) + "/4 familles" },
    { id: "comptable", nom: "Le Comptable du Board", cout: 3, poste: "DÉF", ecole: "Les Pros", archetype: "Sentinelle",
      condition: "Choisir une Philosophie économique",
      identite: "Défend la surface comme un budget.",
      test: (p) => p.philosophies.some((nom) => ["Droits TV majorés", "Mécènes", "Guichets fermés", "Trésor de guerre"].includes(nom)),
      progression: () => "au choix des manches 4/7/10" },
    { id: "phenix", nom: "Le Phénix", cout: 4, poste: "ATT", ecole: "La Grinta", archetype: "Renard",
      condition: "Gagner juste après 3 défaites consécutives",
      identite: "Renaît de chaque série noire.",
      test: (p) => c(p, "phenix") >= 1,
      progression: (p) => c(p, "phenix") ? "fait !" : "série actuelle : " + (p.coachs[0].serie < 0 ? -p.coachs[0].serie + " défaites" : "—") },
    { id: "serrurier", nom: "Le Serrurier", cout: 4, poste: "GAR", ecole: "Catenaccio", archetype: "Mur",
      condition: "Finir un match PvP 0-0",
      identite: "Le 0-0 est son chef-d'œuvre.",
      test: (p) => c(p, "serrurier") >= 1,
      progression: (p) => c(p, "serrurier") ? "fait !" : "0/1" },

    /* ---------- V. Le duo prioritaire ---------- */
    { id: "gus-et-titi", nom: "Gus & Titi — les Increvables", cout: 4, poste: "DUO", ecole: "Le Douzième Homme", archetype: "",
      condition: "Garder Gus OU Titi titulaire jusqu'à la manche 10",
      identite: "Les réservistes du centre devenus légendes — la récompense des fidèles.",
      duo: [
        { nom: "Gus", cout: 4, poste: "GAR", ecole: "Le Douzième Homme", archetype: "Mur", unique: null, icone: true,
          description: "L'increvable gardien du centre — le public l'a rendu légendaire." },
        { nom: "Titi", cout: 4, poste: "ATT", ecole: "Le Douzième Homme", archetype: "Renard", unique: null, icone: true,
          description: "L'increvable renard du centre — il n'a jamais quitté le club." },
      ],
      test: (p) => p.manche >= 10 && p.terrain.some((j) => (j.nom === "Gus" || j.nom === "Titi") && !j.icone),
      progression: (p) => p.terrain.some((j) => (j.nom === "Gus" || j.nom === "Titi") && !j.icone)
        ? "manche " + Math.min(p.manche, 10) + "/10 — tiens bon !" : "Gus et Titi ne sont plus titulaires…" },
  ];

  return { liste, parId: (id) => liste.find((x) => x.id === id) };
})();
if (typeof module !== "undefined") module.exports = ONZE_ICONES;
